#include <stdio.h>
#include "cities.h"

// This script generates a simple SVG map of Tamil Nadu with the route highlighted
// It reads the route_path.txt file generated by the C program

int main() {
    FILE *f = fopen("route_path.txt", "r");
    if (!f) {
        printf("route_path.txt not found. Run the C program first.\n");
        return 1;
    }
    int path[20], n = 0, idx;
    while (fscanf(f, "%d", &idx) == 1) path[n++] = idx;
    fclose(f);
    load_cities();
    FILE *svg = fopen("tamilnadu_route.svg", "w");
    fprintf(svg, "<svg width='700' height='800' xmlns='http://www.w3.org/2000/svg'>\n");
    // Draw cities
    for (int i = 0; i < num_cities; i++) {
        fprintf(svg, "<circle cx='%d' cy='%d' r='10' fill='blue'/><text x='%d' y='%d' font-size='16'>%s</text>\n", cities[i].x, cities[i].y, cities[i].x+12, cities[i].y+4, cities[i].name);
    }
    // Draw route
    fprintf(svg, "<polyline points='");
    for (int i = 0; i < n; i++) {
        fprintf(svg, "%d,%d ", cities[path[i]].x, cities[path[i]].y);
    }
    fprintf(svg, "' fill='none' stroke='red' stroke-width='5'/>\n");
    fprintf(svg, "</svg>\n");
    fclose(svg);
    printf("SVG map generated: tamilnadu_route.svg\n");
    return 0;
}
